test

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -7,9 +7,6 @@ on:
     branches: [ master, main ]
 
 jobs:
-  # =========================================
-  # 🤖 BUILD ANDROID
-  # =========================================
   build-android:
     name: Build Android APK
     runs-on: ubuntu-latest
@@ -59,9 +56,6 @@ jobs:
           name: android-appid
           path: android_appid.txt
 
-  # =========================================
-  # BUILD IOS
-  # =========================================
   build-ios:
     name: Build iOS IPA
     needs: build-android
@@ -77,16 +71,16 @@ jobs:
           flutter-version: 3.24.3
           channel: stable
 
-      - name: Cache Flutter & CocoaPods
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/.pub-cache
-            ios/Pods
-            ~/Library/Caches/CocoaPods
-          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-flutter-
+      # - name: Cache Flutter & CocoaPods
+      #   uses: actions/cache@v4
+      #   with:
+      #     path: |
+      #       ~/.pub-cache
+      #       ios/Pods
+      #       ~/Library/Caches/CocoaPods
+      #     key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.lock') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-flutter-
 
       - name: Install CocoaPods
         run: sudo gem install cocoapods
@@ -134,114 +128,108 @@ jobs:
           name: ios-appid
           path: ios_appid.txt
 
-  # =========================================
-  # MAESTRO TEST (ANDROID)
-  # =========================================
-  maestro-android:
-    name: Maestro Android Tests
-    needs: build-android
-    runs-on: ubuntu-latest
+  # maestro-android:
+  #   name: Maestro Android Tests
+  #   needs: build-android
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v4
 
-      - name: Download Android artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: android-apk
-          path: ./builds/android
+  #     - name: Download Android artifact
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: android-apk
+  #         path: ./builds/android
 
-      - name: Download Android appId
-        uses: actions/download-artifact@v4
-        with:
-          name: android-appid
-          path: .
+  #     - name: Download Android appId
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: android-appid
+  #         path: .
 
-      - name: Setup Android Emulator
-        uses: reactivecircus/android-emulator-runner@v2
-        with:
-          api-level: 34
-          target: google_apis
-          arch: x86_64
-          profile: pixel_6
-          script: |
-            adb kill-server || true
-            adb start-server
-            nohup emulator -avd test -no-snapshot -noaudio -no-window -gpu swiftshader_indirect &
-            adb wait-for-device
-            timeout=300
-            while [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" != "1" ] && [ $timeout -gt 0 ]; do
-              sleep 5
-              timeout=$((timeout - 5))
-              echo "Waiting for emulator... ($timeout sec left)"
-            done
-            adb devices
-            echo "✅ Emulator booted successfully!"
+  #     - name: Setup Android Emulator
+  #       uses: reactivecircus/android-emulator-runner@v2
+  #       with:
+  #         api-level: 34
+  #         target: google_apis
+  #         arch: x86_64
+  #         profile: pixel_6
+  #         script: |
+  #           adb kill-server || true
+  #           adb start-server
+  #           nohup emulator -avd test -no-snapshot -noaudio -no-window -gpu swiftshader_indirect &
+  #           adb wait-for-device
+  #           timeout=300
+  #           while [ "$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')" != "1" ] && [ $timeout -gt 0 ]; do
+  #             sleep 5
+  #             timeout=$((timeout - 5))
+  #             echo "Waiting for emulator... ($timeout sec left)"
+  #           done
+  #           adb devices
+  #           echo "✅ Emulator booted successfully!"
 
-      - name: Start Android Emulator
-        run: |
-          echo "🧩 Creating AVD device (Pixel_6_API_34)..."
-          echo "no" | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" -d "pixel_6" || true
+  #     - name: Start Android Emulator
+  #       run: |
+  #         echo "🧩 Creating AVD device (Pixel_6_API_34)..."
+  #         echo "no" | avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" -d "pixel_6" || true
 
-          echo "🚀 Starting emulator..."
-          nohup emulator -avd test -no-snapshot -noaudio -no-window -gpu swiftshader_indirect &
+  #         echo "🚀 Starting emulator..."
+  #         nohup emulator -avd test -no-snapshot -noaudio -no-window -gpu swiftshader_indirect &
 
-          echo "⏳ Waiting for ADB device..."
-          adb kill-server || true
-          adb start-server
-          adb wait-for-device
+  #         echo "⏳ Waiting for ADB device..."
+  #         adb kill-server || true
+  #         adb start-server
+  #         adb wait-for-device
 
-          boot_completed=""
-          timeout=300
-          while [ -z "$boot_completed" ] && [ $timeout -gt 0 ]; do
-            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
-            if [ "$boot_completed" != "1" ]; then
-              sleep 5
-              timeout=$((timeout - 5))
-              echo "Still waiting... ($timeout sec left)"
-            fi
-          done
+  #         boot_completed=""
+  #         timeout=300
+  #         while [ -z "$boot_completed" ] && [ $timeout -gt 0 ]; do
+  #           boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
+  #           if [ "$boot_completed" != "1" ]; then
+  #             sleep 5
+  #             timeout=$((timeout - 5))
+  #             echo "Still waiting... ($timeout sec left)"
+  #           fi
+  #         done
 
-          if [ "$boot_completed" != "1" ]; then
-            echo "❌ Emulator failed to boot properly!"
-            adb logcat -d
-            exit 1
-          fi
+  #         if [ "$boot_completed" != "1" ]; then
+  #           echo "❌ Emulator failed to boot properly!"
+  #           adb logcat -d
+  #           exit 1
+  #         fi
 
-          adb devices
-          echo "✅ Emulator is ready and online!"
+  #         adb devices
+  #         echo "✅ Emulator is ready and online!"
 
-      # --- ✅ Cài đặt app & chạy test ---
-      - name: Install APK
-        run: |
-          APK_PATH=$(find ./builds/android -name "*.apk" | head -n 1)
-          echo "📦 Installing $APK_PATH"
-          adb install "$APK_PATH" || (echo "Retrying..." && adb install -r "$APK_PATH")
+  #     # --- ✅ Cài đặt app & chạy test ---
+  #     - name: Install APK
+  #       run: |
+  #         APK_PATH=$(find ./builds/android -name "*.apk" | head -n 1)
+  #         echo "📦 Installing $APK_PATH"
+  #         adb install "$APK_PATH" || (echo "Retrying..." && adb install -r "$APK_PATH")
 
-      - name: Install Maestro CLI
-        run: |
-          curl -Ls "https://get.maestro.mobile.dev" | bash
-          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
+  #     - name: Install Maestro CLI
+  #       run: |
+  #         curl -Ls "https://get.maestro.mobile.dev" | bash
+  #         echo "$HOME/.maestro/bin" >> $GITHUB_PATH
 
-      - name: Verify Maestro installation
-        run:
-          maestro --version
+  #     - name: Verify Maestro installation
+  #       run:
+  #         maestro --version
 
-      - name: Run Maestro Android Tests
-        run: |
-          APP_ID=$(cat android_appid.txt)
-          echo "Running Maestro tests for Android appId=$APP_ID"
-          maestro test -e APP_ID=$APP_ID .maestro/login.yaml --format junit --output results-android.xml || true
+  #     - name: Run Maestro Android Tests
+  #       run: |
+  #         APP_ID=$(cat android_appid.txt)
+  #         echo "Running Maestro tests for Android appId=$APP_ID"
+  #         maestro test -e APP_ID=$APP_ID .maestro/login.yaml --format junit --output results-android.xml || true
 
-      - uses: actions/upload-artifact@v4
-        with:
-          name: maestro-android-results
-          path: results-android.xml
+  #     - uses: actions/upload-artifact@v4
+  #       with:
+  #         name: maestro-android-results
+  #         path: results-android.xml
 
-  # =========================================
-  # MAESTRO TEST (IOS)
-  # =========================================
   maestro-ios:
     name: Maestro iOS Tests
     needs: build-ios
@@ -251,67 +239,74 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Download iOS artifact
-        uses: actions/download-artifact@v4
+      - name: Install Xcode
+        working-directory: ios
+        uses: maxim-lobanov/setup-xcode@v1
         with:
-          name: ios-ipa
-          path: ./builds/ios
+          xcode-version: latest
+      - run: xcodebuild -project MyApp.xcodeproj -scheme MyApp -destination 'platform=iOS Simulator,name=iPhone 11'
 
-      - name: Download iOS appId
-        uses: actions/download-artifact@v4
-        with:
-          name: ios-appid
-          path: .
+      # - name: Download iOS artifact
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: ios-ipa
+      #     path: ./builds/ios
 
-      - name: Install Maestro CLI
-        run: |
-          curl -Ls "https://get.maestro.mobile.dev" | bash
-          echo "$HOME/.maestro/bin" >> $GITHUB_PATH
+      # - name: Download iOS appId
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: ios-appid
+      #     path: .
 
-      - name: Verify Maestro installation
-        run:
-          maestro --version
+      # - name: Install Maestro CLI
+      #   run: |
+      #     curl -Ls "https://get.maestro.mobile.dev" | bash
+      #     echo "$HOME/.maestro/bin" >> $GITHUB_PATH
 
-      - name: Start iOS Simulator
-        run: |
-          echo "🔍 Listing available iOS simulators..."
-          xcrun simctl list devices | grep "iPhone" || true
+      # - name: Verify Maestro installation
+      #   run:
+      #     maestro --version
 
-          DEVICE=$(xcrun simctl list devices available | grep -m1 "iPhone" | awk -F '[()]' '{print $2}')
-          if [ -z "$DEVICE" ]; then
-            echo "❌ No iPhone simulator found!"
-            exit 1
-          fi
+      # - name: Start iOS Simulator
+      #   run: |
+      #     echo "🔍 Listing available iOS simulators..."
+      #     xcrun simctl list devices | grep "iPhone" || true
 
-          echo "📱 Booting simulator with UDID: $DEVICE"
-          xcrun simctl boot "$DEVICE" || true
-          xcrun simctl bootstatus "$DEVICE" -b
-          sleep 10
-          echo "✅ iOS Simulator ready"
+      #     DEVICE=$(xcrun simctl list devices available | grep -m1 "iPhone" | awk -F '[()]' '{print $2}')
+      #     if [ -z "$DEVICE" ]; then
+      #       echo "❌ No iPhone simulator found!"
+      #       exit 1
+      #     fi
 
-      - name: Install iOS app to simulator
-        run: |
-          DEVICE=$(xcrun simctl list devices booted | grep -m1 "iPhone" | awk -F '[()]' '{print $2}')
-          IPA_PATH=$(find ./builds/ios -name "*.ipa" | head -n 1)
+      #     echo "📱 Booting simulator with UDID: $DEVICE"
+      #     xcrun simctl boot "$DEVICE" || true
+      #     xcrun simctl bootstatus "$DEVICE" -b
+      #     sleep 10
+      #     echo "✅ iOS Simulator ready"
 
-          if [ -z "$IPA_PATH" ]; then
-            echo "❌ No .ipa file found in ./builds/ios"
-            exit 1
-          fi
+      # - name: Install iOS app to simulator
+      #   run: |
+      #     DEVICE=$(xcrun simctl list devices booted | grep -m1 "iPhone" | awk -F '[()]' '{print $2}')
+      #     IPA_PATH=$(find ./builds/ios -name "*.ipa" | head -n 1)
 
-          echo "📦 Installing app to simulator: $DEVICE"
-          TMP_DIR=$(mktemp -d)
-          unzip -q "$IPA_PATH" -d "$TMP_DIR"
-          APP_PATH=$(find "$TMP_DIR" -name "*.app" | head -n 1)
+      #     if [ -z "$IPA_PATH" ]; then
+      #       echo "❌ No .ipa file found in ./builds/ios"
+      #       exit 1
+      #     fi
 
-          if [ -z "$APP_PATH" ]; then
-            echo "❌ Could not find .app inside the .ipa file"
-            exit 1
-          fi
+      #     echo "📦 Installing app to simulator: $DEVICE"
+      #     TMP_DIR=$(mktemp -d)
+      #     unzip -q "$IPA_PATH" -d "$TMP_DIR"
+      #     APP_PATH=$(find "$TMP_DIR" -name "*.app" | head -n 1)
 
-          xcrun simctl install "$DEVICE" "$APP_PATH"
-          xcrun simctl launch "$DEVICE" $(cat ios_appid.txt) || true
-          echo "✅ App installed successfully"
+      #     if [ -z "$APP_PATH" ]; then
+      #       echo "❌ Could not find .app inside the .ipa file"
+      #       exit 1
+      #     fi
+
+      #     xcrun simctl install "$DEVICE" "$APP_PATH"
+      #     xcrun simctl launch "$DEVICE" $(cat ios_appid.txt) || true
+      #     echo "✅ App installed successfully"
 
       - name: Run Maestro iOS Tests
         run: |
